public enum IMIONA {
    ADAM(1), AGATA(0), ALAN(1), ALEKSANDRA(0), ANDRZEJ(1), ANETA(0), ANTONI(1), AGNIESZKA(0), BARTOSZ(1), BARBARA(0),
    CEZARY(1), CELINA(0), CYRYL(1), DARIUSZ(1), DANIEL(1), DAGMARA(0), DAMIAN(1), DOROTA(0), EDWARD(1), ELIZA(0),
    FILIP(1), FELICJA(0), FRANCISZEK(1), FAUSTYNA(0), GRZEGORZ(1), GABRIELA(0), HENRYK(1), HALINA(0), IRENEUSZ(1), IWONA(0),
    JAKUB(1), JOANNA(0), JAN(1), JADWIGA(0), KACPER(1), KATARZYNA(0), KRZYSZTOF(1), KAROLINA(0), LUKASZ(1), LIDIA(0),
    MAREK(1), MARIA(0), MATEUSZ(1), MAGDALENA(0), MICHAL(1), MONIKA(0), NORBERT(1), NATALIA(0), OLIWIER(1), OLIWIA(0),
    PIOTR(1), PAULA(0), PAWEL(1), PATRYCJA(0), ROBERT(1), RENATA(0), ROMAN(1), ROZA(0), SEBASTIAN(1), SARA(0),
    TOMASZ(1), TATIANA(0), TADEUSZ(1), TERESA(0), URSZULA(0), WOJCIECH(1), WERONIKA(0), WIKTOR(1), WANDA(0),
    ZBIGNIEW(1), ZOFIA(0), ZYGMUNT(1), ZUZANNA(0), LUCJA(0), JANUSZ(1), JOLANTA(0), ADRIAN(1), BRUNO(1), BRYGIDA(0),
    DAWID(1), ELIASZ(1), ELZBIETA(0), FABIAN(1), FELIKS(1), GUSTAW(1), GRAZYNA(0), HUBERT(1), HELENA(0), IWO(1),
    IDA(0), JULIAN(1), JUSTYNA(0), KONRAD(1), KORNELIA(0);

    private final int value;
    private IMIONA(int value){
        this.value = value;
    }
    public int getValue(){
        return value;
    }
}
